import turtle
turtle.bgcolor("black")
turtle.pencolor("red")
turtle.fillcolor("yellow")
turtle.begin_fill()
turtle.goto(0,100)
turtle.forward(100)
turtle.penup()
turtle.home()
turtle.pendown()
turtle.goto(0,-100)
turtle.pendown()
turtle.left(180)
turtle.forward(100)
turtle.penup()
turtle.home()
turtle.pendown()
turtle.forward(100)
turtle.right(90)
turtle.forward(100)
turtle.penup()
turtle.home()
turtle.pendown()
turtle.right(180)
turtle.forward(100)
turtle.right(90)
turtle.forward(100)
turtle.penup()
turtle.goto(-120,0)
turtle.forward(120)
turtle.right(90)
turtle.forward(240)
turtle.right(90)
turtle.forward(240)
turtle.right(90)
turtle.forward(240)
turtle.right(90)
turtle.forward(240)
turtle.right(90)
turtle.end_fill()
turtle.penup()
turtle.goto(0,-192)
turtle.pendown()
turtle.circle(200)
    


