import turtle
a = turtle.Turtle()
def building(lenth,breath,color,fill):
    a.color(color,fill)
    a.begin_fill()
    for i in range(2):
        a.forward(lenth)
        a.left(90)
        a.forward(breath)
        a.left(90)
    a.end_fill()
a.penup()
a.goto(-300,-250)
a.pendown()
building(600,250,"black","black")
a.penup()
a.goto(-200,0)
a.pendown()
building(40,100,"red","blue")
a.penup()
a.goto(-165,0)
a.pendown()
building(20,200,"blue","red")
a.penup()
a.goto(-120,0)
a.pendown()
building(40,30,"brown","green")
a.penup()
a.goto(-70,0)
a.pendown()
building(30,180,"green","grey")
a.penup()
a.goto(-30,0)
a.pendown()
building(20,80,"grey","green")
a.penup()
a.goto(0,0)
a.pendown()
building(30,120,"pink","blue")
a.penup()
a.goto(50,0)
a.pendown()
building(60,180,"grey","red")
a.penup()
a.goto(120,0)
a.pendown()
building(50,180,"green","grey")


